FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest

RUN rustup component add rustfmt

RUN dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:amd64 clang
