FROM rust:slim

RUN apt update && apt upgrade -y
RUN apt install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross
RUN dpkg --add-architecture arm64
RUN apt update && apt upgrade -y
RUN apt install -y libdbus-1-dev:arm64
RUN apt install -y libssl-dev:arm64
RUN apt install -y libfontconfig-dev:arm64
RUN apt install -y libsqlite3-dev:arm64
RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu
RUN rustup component add rustfmt

WORKDIR /app

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
    PKG_CONFIG_ALLOW_CROSS=true \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++ \
    RUSTFLAGS='-C target-feature=+crt-static'

CMD ["cargo", "build", "--target", "aarch64-unknown-linux-gnu"]
