FROM --platform=$BUILDPLATFORM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN rustup component add rustfmt

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:arm64 clang
